package org.example.service;

/**
 * Lists the possible values for booking status.
 */
public enum BookingStatus {
    SUCCESS,
    BLANK_CUSTOMER_NAME,
    BLANK_SLOT_TIME,
    INVALID_DURATION,
    INVALID_PARTICIPANT_COUNT,
    INVALID_APPOINTMENT_RULES,
    SLOT_NOT_FOUND,
    SLOT_ALREADY_BOOKED,
    UNAUTHORIZED,
    APPOINTMENT_NOT_FOUND,
    APPOINTMENT_NOT_FUTURE,
    APPOINTMENT_ALREADY_CANCELLED,
    APPOINTMENT_ALREADY_ATTENDED,
    APPOINTMENT_ALREADY_COMPLETED,
    APPOINTMENT_NOT_ATTENDED,
    UPDATE_FAILED
}
