package org.example.service;

/**
 * Lists the possible values for booking status.
 */
public enum BookingStatus {
    SUCCESS,
    BLANK_CUSTOMER_NAME,
    BLANK_PHONE_NUMBER,
    BLANK_SLOT_TIME,
    INVALID_DURATION,
    INVALID_PARTICIPANT_COUNT,
    INVALID_PHONE_NUMBER,
    INVALID_SLOT_DATE_TIME,
    INVALID_APPOINTMENT_RULES,
    DUPLICATE_SLOT,
    SLOT_NOT_FOUND,
    SLOT_ALREADY_BOOKED,
    WAITLISTED,
    WAITLIST_ALREADY_EXISTS,
    WAITLIST_ALREADY_BOOKED,
    WAITLIST_PROMOTION_FAILED,
    UNAUTHORIZED,
    APPOINTMENT_NOT_FOUND,
    APPOINTMENT_NOT_FUTURE,
    APPOINTMENT_ALREADY_CANCELLED,
    APPOINTMENT_ALREADY_ATTENDED,
    APPOINTMENT_ALREADY_NOT_ATTENDED,
    APPOINTMENT_ALREADY_COMPLETED,
    APPOINTMENT_NOT_ATTENDED,
    APPOINTMENT_NOT_COMPLETED,
    FEEDBACK_ALREADY_SUBMITTED,
    INVALID_RATING,
    UPDATE_FAILED
}
